// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/groups/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groups/[id].get').default>>>>
    }
    '/api/groups/:id/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groups/[id]/dashboard.get').default>>>>
    }
    '/api/groups/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groups/create.post').default>>>>
    }
    '/api/groups': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/groups/index.get').default>>>>
    }
    '/api/students/:id/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[id]/messages.get').default>>>>
    }
    '/api/students/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/join.post').default>>>>
    }
    '/ws/group/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/ws/group/[id]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}